version: "3.8"

services:
  postgres:
    container_name: costs_postgres
    build:
      context: ./postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=costs
      - POSTGRES_USER=costs
      - POSTGRES_PASSWORD=costs

  backend:
    container_name: costs_backend
    build:
      context: ./backend
    ports:
      - 3000:3000
    depends_on:
      - postgres
    restart: always
    environment:
      - DATABASE_URL=postgresql://costs:costs@localhost:5432/costs?schema=public
      - ACCESS_TOKEN_SECRET=098f0a6scvjk1ahvl435ka8809s8ac56csa46cs542csa90c8sa90cs7
      - REFRESH_TOKEN_SECRET=7csa90c88789f6sa08fh7m6567j567a5v7as9ghag5903gfacsmnvka1m

  frontend:
    container_name: costs_frontend
    build:
      context: ./frontend
    ports:
     - 4173:4173